import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react/cjs/react.production.min';
import { useAppContext } from '../../providers/AppProvider';
import {
	queryRecipesFromNameList,
	testQuery,
	queryAllRecipes,
} from '../../graphql/recipeQuery';
import styles from './Splash.module.scss';

const Splash = () => {
	// const app = useAppContext();
	// console.log('app: ', app);

	// console.log('recipes:', queryRecipesFromNameList(['hot dog', 'beef stew']));
	const recipes = queryAllRecipes();
	console.log('recipes:', recipes);

	return (
		<div className={styles.Splash}>
			<Head>
				<title>Reverse Recipe</title>
				<meta
					name="description"
					content="Generated by Reverse Recipe"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Image
				src="/rr-logo-light.svg"
				width="400"
				height="100%"
				layout="intrinsic"
				alt="Reverse Recipe Logo"
			/>
		</div>
	);
};

export default Splash;
